create sequence confirmation_token_sequence start 1 increment 1;
create sequence user_sequence start 1 increment 1;

    create table confirmation_token (
       id int8 not null,
        confirmed_at timestamp,
        created_at timestamp not null,
        expires_at timestamp not null,
        token varchar(255) not null,
        app_user_id int8 not null,
        primary key (id)
    );

    create table tb_address (
       id int8 generated by default as identity,
        area varchar(255),
        city varchar(50),
        number varchar(30),
        state varchar(30),
        street varchar(255),
        zip_code varchar(30),
        primary key (id)
    );

    create table tb_app_role (
       id int8 generated by default as identity,
        name varchar(50),
        primary key (id)
    );

    create table tb_loan (
       id int8 not null,
        cod varchar(255) not null,
        confirmed_at timestamp,
        created_at timestamp,
        initial_date date,
        intervals int4 not null,
        status int4,
        value int8,
        app_user_id int8 not null,
        primary key (id)
    );

    create table tb_user (
       id int8 not null,
        alias varchar(50),
        cpf varchar(50),
        email varchar(255) not null,
        enabled boolean,
        income int8,
        locked boolean,
        name varchar(255) not null,
        password varchar(64) not null,
        phone_number varchar(50),
        address_id int8,
        primary key (id)
    );

    create table tb_user_roles (
       user_id int8 not null,
        roles_id int8 not null
    );

    alter table if exists tb_loan 
       add constraint name_cod_unique unique (cod);

    alter table if exists tb_user 
       add constraint name_email_unique unique (email);

    alter table if exists tb_user 
       add constraint name_cpf_unique unique (cpf);

    alter table if exists confirmation_token 
       add constraint FKoc9jjibot8o21era92gqoqwvj 
       foreign key (app_user_id) 
       references tb_user;

    alter table if exists tb_loan 
       add constraint FKgv2e6whgxyns4rh6jqbxpglo9 
       foreign key (app_user_id) 
       references tb_user;

    alter table if exists tb_user 
       add constraint FK3rb71vq3k8rmbps3grjwvcqth 
       foreign key (address_id) 
       references tb_address;

    alter table if exists tb_user_roles 
       add constraint FKb2jrx0ndr2v9awpohmylphc2e 
       foreign key (roles_id) 
       references tb_app_role;

    alter table if exists tb_user_roles 
       add constraint FK19t64ocsol5x06fy2cytp7gey 
       foreign key (user_id) 
       references tb_user;
